# Generated by Django 2.2.28 on 2022-10-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_fdsfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rewrwe',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
