# Generated by Django 2.2.28 on 2022-10-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_rewrwe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rerere',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
