# Generated by Django 2.2.28 on 2022-10-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_rerere'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ffeeww',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
