# Generated by Django 2.2.28 on 2022-10-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_ffeeww'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eeaaqwq',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
