# Generated by Django 2.2.28 on 2022-11-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_oooo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='oooo',
        ),
        migrations.AddField(
            model_name='user',
            name='xzxzxx',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
