# Generated by Django 2.2.28 on 2022-11-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20221101_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ffeeww',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rerere',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rewrwe',
        ),
    ]
