# Generated by Django 2.2.28 on 2022-11-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20221101_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vvvvffff',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
