# Generated by Django 2.2.28 on 2022-11-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20221101_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eeeaaa',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
